# Generated by Django 6.0.7 on 2026-08-04 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_dischargerequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='patient_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
