# Generated by Django 6.0.7 on 2026-07-28 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='billing_cycle',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], default='monthly', max_length=20),
        ),
        migrations.AddField(
            model_name='tenant',
            name='grace_period_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='next_billing_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='plan',
            field=models.CharField(choices=[('basic', 'Basic'), ('pro', 'Pro'), ('enterprise', 'Enterprise')], default='basic', max_length=20),
        ),
        migrations.AddField(
            model_name='tenant',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('trial', 'Trial'), ('overdue', 'Overdue'), ('suspended', 'Suspended')], default='trial', max_length=20),
        ),
        migrations.AddField(
            model_name='tenant',
            name='trial_ends_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
