# Generated by Django 6.0.7 on 2026-07-29 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_tenant_billing_cycle_tenant_grace_period_end_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_color', models.CharField(default='#2563EB', max_length=7)),
                ('secondary_color', models.CharField(default='#10B981', max_length=7)),
                ('accent_color', models.CharField(default='#F59E0B', max_length=7)),
                ('sidebar_color', models.CharField(default='#1E293B', max_length=7)),
                ('font_family', models.CharField(default='Inter, system-ui, sans-serif', max_length=100)),
                ('company_name', models.CharField(default='RehabYangu', max_length=200)),
                ('tagline', models.CharField(blank=True, max_length=200, null=True)),
                ('footer_text', models.CharField(default='RehabYangu – Powered by Weiraro Technologies', max_length=200)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='favicons/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config', to='tenants.tenant')),
            ],
        ),
    ]
