# Generated by Django 6.0.7 on 2026-08-02 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_tenantconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='monthly_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
