/** @type {import('tailwindcss').Config} */
export default {
  darkMode: ["class"],
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  safelist: [
    "bg-[#0f2e3d]",
    "bg-[#1d5a70]",
    "text-[#0f2e3d]",
    "text-[#1d5a70]",
    "border-[#1d5a70]",
    "bg-dark",
    "text-display",
    "text-page-title",
    "text-section-title",
    "text-component-title",
    "text-body",
    "text-secondary",
    "text-caption",
    "font-numeric",
  ],
  theme: {
    extend: {
      colors: {
        primary: {
          DEFAULT: "#1D5A70",
          hover: "#184A5C",
          subtle: "#E8F0F2",
          50: '#eaf3f6',
          100: '#dce8ec',
          200: '#b9d1d9',
          300: '#96bac6',
          400: '#73a3b3',
          500: '#508ca0',
          600: '#1d5a70',
          700: '#0f2e3d',
          800: '#09222e',
          900: '#05141a',
        },
        dark: {
          DEFAULT: "#0F2E3D",
          panel: "#0B2531",
        },
        background: "#F4F6F7",
        surface: "#FFFFFF",
        accent: {
          DEFAULT: "#237A57",
          subtle: "#E7F3ED",
          50: '#ddf0e7',
          100: '#b8e0d0',
          200: '#90d0b8',
          300: '#68bfa0',
          400: '#40af88',
          500: '#2e9b6f',
          600: '#237a57',
          700: '#1a5e42',
          800: '#12422e',
          900: '#09261a',
        },
        warning: {
          DEFAULT: "#8A611F",
          subtle: "#FBF4E9",
        },
        danger: {
          DEFAULT: "#8C3A2F",
          subtle: "#FAECEA",
        },
        border: {
          DEFAULT: "#DCE2E4",
          strong: "#B9C3C6",
        },
        ink: {
          primary: "#1A2B31",
          secondary: "#5B6B70",
          muted: "#8A989C",
        },
        secondary: {
          50: '#f5f6f7',
          100: '#eceef0',
          200: '#d3d7db',
          300: '#b6bcc2',
          400: '#8f979f',
          500: '#5b6b76',
          600: '#3d454c',
          700: '#2f363b',
          800: '#1f2428',
          900: '#121518',
        },
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        card: { DEFAULT: "hsl(var(--card))", foreground: "hsl(var(--card-foreground))" },
        popover: { DEFAULT: "hsl(var(--popover))", foreground: "hsl(var(--popover-foreground))" },
        muted: { DEFAULT: "hsl(var(--muted))", foreground: "hsl(var(--muted-foreground))" },
      },
      fontFamily: {
        sans: [
          "Inter",
          "-apple-system",
          "BlinkMacSystemFont",
          "Segoe UI",
          "sans-serif",
        ],
        numeric: ["IBM Plex Sans", "Inter", "sans-serif"],
        mono: ['IBM Plex Sans', 'monospace'],
      },
      fontSize: {
        display: ["32px", { lineHeight: "1.25", fontWeight: "700" }],
        "page-title": ["24px", { lineHeight: "1.3", fontWeight: "700" }],
        "section-title": ["19px", { lineHeight: "1.35", fontWeight: "700" }],
        "component-title": ["16px", { lineHeight: "1.4", fontWeight: "600" }],
        body: ["15px", { lineHeight: "1.6", fontWeight: "400" }],
        secondary: ["14px", { lineHeight: "1.55", fontWeight: "400" }],
        caption: [
          "12px",
          { lineHeight: "1.4", fontWeight: "600", letterSpacing: "0.04em" },
        ],
      },
      borderRadius: {
        card: "14px",
        btn: '0.5rem',
        input: '0.5rem',
      },
      boxShadow: {
        card: "0 1px 2px rgba(15, 46, 61, 0.06), 0 1px 1px rgba(15, 46, 61, 0.04)",
        raised: "0 4px 12px rgba(15, 46, 61, 0.10)",
        'card-hover': '0 8px 24px rgba(0,0,0,0.08)',
        dropdown: '0 4px 16px rgba(0,0,0,0.08)',
        modal: '0 16px 48px rgba(0,0,0,0.12)',
      },
      keyframes: {
        fadeIn: {
          "0%": { opacity: "0" },
          "100%": { opacity: "1" },
        },
        cardIn: {
          "0%": { opacity: "0", transform: "translateY(12px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        'slide-up': {
          '0%': { opacity: '0', transform: 'translateY(25px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        'float': {
          '0%, 100%': { transform: 'translateY(0)' },
          '50%': { transform: 'translateY(-8px)' },
        },
      },
      animation: {
        "fade-in": "fadeIn 0.5s ease-out both",
        "card-in": "cardIn 0.5s cubic-bezier(0.16, 1, 0.3, 1) both",
        'slide-up': 'slide-up 0.7s ease-out forwards',
        'float': 'float 6s ease-in-out infinite',
      },
    },
  },
  plugins: [],
}
