# Generated by Django 6.0.7 on 2026-07-30 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='download_token',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='sponsor_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='token_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='cover_letter_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
