# Generated by Django 6.0.7 on 2026-07-30 15:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_invoice_download_token_invoice_sponsor_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='download_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
