from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):
    initial = True
    dependencies = [('patients', '0006_emr_admissions_treatment_plans'), ('tenants', '0008_tenantconfig_onboarding_completed_at'), migrations.swappable_dependency(settings.AUTH_USER_MODEL)]
    operations = [
        migrations.CreateModel(name='Medication', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('name', models.CharField(max_length=200)), ('strength', models.CharField(max_length=100)), ('form', models.CharField(max_length=100)), ('category', models.CharField(blank=True, max_length=100)), ('is_controlled_substance', models.BooleanField(default=False)), ('created_at', models.DateTimeField(auto_now_add=True)), ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medications', to='tenants.tenant'))], options={'ordering': ['name', 'strength']}),
        migrations.CreateModel(name='Prescription', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('dose', models.CharField(max_length=100)), ('frequency', models.CharField(help_text='For example: every 8 hours', max_length=100)), ('duration_days', models.PositiveIntegerField()), ('start_at', models.DateTimeField()), ('instructions', models.TextField(blank=True)), ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='active', max_length=20)), ('created_at', models.DateTimeField(auto_now_add=True)), ('medication', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescriptions', to='medications.medication')), ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescriptions', to='patients.patient')), ('prescribing_clinician', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescriptions_written', to=settings.AUTH_USER_MODEL)), ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='tenants.tenant'))], options={'ordering': ['-start_at']}),
        migrations.CreateModel(name='MedicationAdministrationRecord', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('administered_at', models.DateTimeField()), ('dose', models.CharField(max_length=100)), ('route', models.CharField(max_length=100)), ('notes', models.TextField(blank=True)), ('created_at', models.DateTimeField(auto_now_add=True)), ('given_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medications_given', to=settings.AUTH_USER_MODEL)), ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='administrations', to='medications.prescription'))], options={'ordering': ['-administered_at']}),
        migrations.AddConstraint(model_name='medication', constraint=models.UniqueConstraint(fields=('tenant', 'name', 'strength', 'form'), name='unique_tenant_medication')),
    ]
