# Generated by Django 6.0.7 on 2026-08-04 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='product_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='category',
            field=models.CharField(choices=[('DRUG', 'Drug/Medication'), ('CONSUMABLE', 'Consumable'), ('EQUIPMENT', 'Medical Equipment'), ('SERVICE', 'Rehab Service')], max_length=20),
        ),
    ]
