# Generated by Django 6.0.7 on 2026-07-28 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_inventoryitem_cost_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='category',
            field=models.CharField(choices=[('DRUG', 'Drug/Medication'), ('CONSUMABLE', 'Consumable'), ('EQUIPMENT', 'Medical Equipment'), ('SERVICE', 'Rehab Service')], max_length=20),
        ),
    ]
