import { useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { z } from 'zod';
import { zodResolver } from '@hookform/resolvers/zod';
import { useForm } from 'react-hook-form';
import { PlusIcon } from '@heroicons/react/24/outline';
import { emrApi, type Patient } from '../api/emr';
import { usePermission } from '../hooks/usePermission';
import { Button } from '../components/ui/Button';
import { Badge } from '../components/ui/Badge';
import { Table } from '../components/ui/Table';
import { Modal } from '../components/ui/Modal';
import { Field, SelectField, TextareaField } from '../components/ui/FormFields';
import { EmptyState } from '../components/EmptyState';
import { ErrorBanner } from '../components/ErrorBanner';
import { SkeletonTable } from '../components/Skeleton';

const schema = z.object({ patient: z.coerce.number().positive('Select a patient'), intake_date: z.string().min(1, 'Intake date is required'), room: z.string().min(1, 'Room is required'), bed: z.string().min(1, 'Bed is required'), primary_diagnosis: z.string().min(1, 'Primary diagnosis is required'), psychiatric_diagnosis: z.string().optional(), substance_use_history: z.string().optional(), medical_history: z.string().optional() });
type Values = z.infer<typeof schema>;
function NewAdmission({ onClose, sensitive, patientId }: { onClose: () => void; sensitive: boolean; patientId?: number }) {
  const qc = useQueryClient(); const patients = useQuery<Patient[]>({ queryKey: ['patients'], queryFn: emrApi.patients });
  const form = useForm<Values>({ resolver: zodResolver(schema) as any, defaultValues: { patient: patientId, intake_date: new Date().toISOString().slice(0, 10) } });
  const create = useMutation({ mutationFn: (v: Values) => emrApi.createAdmission({ ...v, substance_use_history: v.substance_use_history || undefined }), onSuccess: () => { qc.invalidateQueries({ queryKey: ['admissions'] }); onClose(); } });
  return <Modal open onOpenChange={(o) => !o && onClose()} title="Admit patient"><form className="space-y-5" onSubmit={form.handleSubmit((v) => create.mutate(v))}><SelectField label="Patient" error={form.formState.errors.patient?.message} {...form.register('patient')}><option value="">Select patient</option>{patients.data?.filter(p => p.status !== 'discharged').map(p => <option key={p.id} value={p.id}>{p.first_name} {p.last_name} · {p.patient_id}</option>)}</SelectField><div className="grid grid-cols-2 gap-4"><Field label="Intake date" type="date" error={form.formState.errors.intake_date?.message} {...form.register('intake_date')} /><Field label="Room" placeholder="A-12" error={form.formState.errors.room?.message} {...form.register('room')} /><Field label="Bed" placeholder="02" error={form.formState.errors.bed?.message} {...form.register('bed')} /></div><TextareaField label="Primary diagnosis" rows={2} error={form.formState.errors.primary_diagnosis?.message} {...form.register('primary_diagnosis')} />{sensitive && <><TextareaField label="Psychiatric diagnosis" rows={2} {...form.register('psychiatric_diagnosis')} /><TextareaField label="Substance use history" rows={2} {...form.register('substance_use_history')} /></>}<TextareaField label="Medical history" rows={2} {...form.register('medical_history')} />{create.isError && <ErrorBanner>Unable to create this admission. The bed may already be occupied.</ErrorBanner>}<div className="flex justify-end gap-3"><Button type="button" variant="secondary" className="w-auto" onClick={onClose}>Cancel</Button><Button className="w-auto" isLoading={create.isPending}>Admit patient</Button></div></form></Modal>;
}
function Discharge({ admission, close }: { admission: any; close: () => void }) { const qc = useQueryClient(); const form = useForm<{ reason: string }>({ defaultValues: { reason: '' } }); const mutation = useMutation({ mutationFn: (v: { reason: string }) => emrApi.dischargeAdmission(admission.id, v.reason), onSuccess: () => { qc.invalidateQueries({ queryKey: ['admissions'] }); qc.invalidateQueries({ queryKey: ['patients'] }); close(); } }); return <Modal open onOpenChange={o => !o && close()} title="Discharge patient"><form className="space-y-5" onSubmit={form.handleSubmit(v => mutation.mutate(v))}><p className="text-body text-secondary-600">Discharge <strong>{admission.patient_name}</strong>. This releases room {admission.room}, bed {admission.bed}.</p><TextareaField label="Reason for discharge" rows={3} error={form.formState.errors.reason?.message} {...form.register('reason', { required: 'Reason is required' })} />{mutation.isError && <ErrorBanner>We could not discharge this patient. Try again.</ErrorBanner>}<div className="flex justify-end gap-3"><Button type="button" variant="secondary" className="w-auto" onClick={close}>Cancel</Button><Button variant="danger" className="w-auto" isLoading={mutation.isPending}>Discharge patient</Button></div></form></Modal> }
export default function Admissions() {
  const referralPatientId = Number(new URLSearchParams(window.location.search).get('patient')) || undefined;
  const [open, setOpen] = useState(Boolean(referralPatientId)); const [discharging, setDischarging] = useState<any>(null); const canWrite = usePermission('clinical.write') || usePermission('admission:create'); const sensitive = usePermission('clinical.sensitive.write');
  const query = useQuery({ queryKey: ['admissions'], queryFn: () => emrApi.admissions() });
  const rows = (items: any[], active: boolean) => <Table><thead><tr><th>Patient</th><th>Admission</th><th>Intake date</th><th>Room / bed</th><th>Primary diagnosis</th><th>Days</th><th>Status</th>{active && <th>Action</th>}</tr></thead><tbody>{items.map((a: any) => <tr key={a.id}><td className="font-medium text-secondary-800">{a.patient_name || `Patient #${a.patient}`}</td><td className="font-mono text-sm">{a.admission_number}</td><td>{new Date(a.intake_date).toLocaleDateString()}</td><td>{a.room || '—'} {a.bed ? `· ${a.bed}` : ''}</td><td className="max-w-xs truncate">{a.primary_diagnosis || '—'}</td><td>{a.length_of_stay_days ?? 0}</td><td><Badge tone={active ? 'success' : 'neutral'}>{active ? 'admitted' : 'discharged'}</Badge></td>{active && <td>{canWrite && <Button variant="secondary" className="w-auto px-3 py-2" onClick={() => setDischarging(a)}>Discharge</Button>}</td>}</tr>)}</tbody></Table>;
  const active = query.data?.filter((a: any) => !a.discharge_date) || [], discharged = query.data?.filter((a: any) => a.discharge_date) || [];
  return <div className="space-y-6"><div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-center"><div><h1 className="text-page-title text-secondary-800">Admissions</h1><p className="text-body text-secondary-500">Current and historical patient stays</p></div>{canWrite && <Button className="w-auto" onClick={() => setOpen(true)}><PlusIcon className="h-4 w-4" />Admit patient</Button>}</div>{query.isLoading ? <SkeletonTable rows={5} cols={7} /> : query.isError ? <ErrorBanner>We could not load admissions. Refresh the page or try again shortly.</ErrorBanner> : !query.data?.length ? <EmptyState title="No admissions" description="Admit a patient when they begin care." actionLabel={canWrite ? 'Admit patient' : undefined} onAction={canWrite ? () => setOpen(true) : undefined} iconType="inbox" /> : <><section className="space-y-3"><h2 className="text-section-title text-secondary-800">Active admissions</h2>{active.length ? rows(active, true) : <p className="text-body text-secondary-500">No active admissions.</p>}</section><section className="space-y-3"><h2 className="text-section-title text-secondary-800">Discharged admissions</h2>{discharged.length ? rows(discharged, false) : <p className="text-body text-secondary-500">No discharged admissions.</p>}</section></>}{open && <NewAdmission onClose={() => setOpen(false)} sensitive={sensitive} patientId={referralPatientId} />}{discharging && <Discharge admission={discharging} close={() => setDischarging(null)} />}</div>;
}
