import { useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { PlusIcon, PencilSquareIcon } from '@heroicons/react/24/outline';
import { adminApi, type Plan } from '../../api/admin';
import { Modal } from '../../components/ui/Modal';
import { useToast } from '../../context/ToastContext';

const features = ['patients', 'clinical_notes', 'vitals', 'appointments', 'billing', 'advanced_billing', 'inventory', 'hr', 'branches', 'analytics', 'mfa', 'priority_support'];
const money = (price: string) => new Intl.NumberFormat('en-KE', { style: 'currency', currency: 'KES', maximumFractionDigits: 0 }).format(Number(price));
const initial = { name: '', code: '', description: '', price_monthly: '0', max_users: '5', feature_flags: {} as Record<string, boolean>, is_active: true };

function PlanForm({ plan, onClose }: { plan?: Plan; onClose: () => void }) {
  const [form, setForm] = useState(plan ? { ...plan, max_users: plan.max_users === null ? '' : String(plan.max_users) } : initial);
  const [confirmDeactivation, setConfirmDeactivation] = useState(false);
  const qc = useQueryClient(); const { showToast } = useToast();
  const mutation = useMutation({ mutationFn: () => {
    const data = { ...form, code: form.code.toLowerCase().replace(/[^a-z0-9-]/g, '-'), max_users: form.max_users === '' ? null : Number(form.max_users) };
    return plan ? adminApi.updatePlan(plan.id, data) : adminApi.createPlan(data);
  }, onSuccess: () => { qc.invalidateQueries({ queryKey: ['admin-plans'] }); showToast(`Plan ${plan ? 'updated' : 'created'}.`, 'success'); onClose(); } });
  const submit = () => { if (plan?.is_active && !form.is_active) { setConfirmDeactivation(true); return; } mutation.mutate(); };
  return <><Modal open onOpenChange={(open) => !open && onClose()} title={plan ? 'Edit subscription plan' : 'Add subscription plan'}><form className="space-y-4" onSubmit={(event) => { event.preventDefault(); submit(); }}>
    <div className="grid gap-4 sm:grid-cols-2"><label className="form-label">Name<input required className="input-field mt-1" value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} /></label><label className="form-label">Code<input required className="input-field mt-1" value={form.code} onChange={(e) => setForm({ ...form, code: e.target.value })} /></label><label className="form-label">Monthly price (KES)<input required min="0" type="number" className="input-field mt-1" value={form.price_monthly} onChange={(e) => setForm({ ...form, price_monthly: e.target.value })} /></label><label className="form-label">User limit <span className="font-normal">(blank = unlimited)</span><input min="1" type="number" className="input-field mt-1" value={form.max_users} onChange={(e) => setForm({ ...form, max_users: e.target.value })} /></label></div>
    <label className="form-label">Description<textarea className="input-field mt-1" value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })} /></label>
    <fieldset><legend className="form-label mb-2">Enabled modules</legend><div className="grid grid-cols-2 gap-2 sm:grid-cols-3">{features.map((feature) => <label key={feature} className="flex min-h-11 items-center gap-2 text-sm capitalize"><input type="checkbox" checked={Boolean(form.feature_flags[feature])} onChange={(e) => setForm({ ...form, feature_flags: { ...form.feature_flags, [feature]: e.target.checked } })} />{feature.replace('_', ' ')}</label>)}</div></fieldset>
    <label className="flex min-h-11 items-center gap-2 text-sm"><input type="checkbox" checked={form.is_active} onChange={(e) => setForm({ ...form, is_active: e.target.checked })} />Available for assignment</label>
    {mutation.isError && <p role="alert" className="text-sm text-danger">Unable to save this plan. Check the code and values.</p>}<button disabled={mutation.isPending} className="btn-primary w-full justify-center">{mutation.isPending ? 'Saving…' : 'Save plan'}</button>
  </form></Modal>{confirmDeactivation && <Modal open onOpenChange={(open) => !open && setConfirmDeactivation(false)} title="Deactivate subscription plan"><p className="text-secondary text-ink-secondary">This stops new tenant assignments. It cannot be deactivated while active tenants still use it.</p><div className="mt-6 flex justify-end gap-3"><button className="btn-secondary" onClick={() => setConfirmDeactivation(false)}>Cancel</button><button disabled={mutation.isPending} className="btn-primary" onClick={() => mutation.mutate()}>{mutation.isPending ? 'Deactivating…' : 'Deactivate plan'}</button></div></Modal>}</>;
}

export default function Plans() { const { data, isLoading, isError, refetch } = useQuery({ queryKey: ['admin-plans'], queryFn: adminApi.plans }); const [editing, setEditing] = useState<Plan | undefined>(); const [creating, setCreating] = useState(false);
  if (isLoading) return <div className="grid gap-4 md:grid-cols-3">{[1,2,3].map((key) => <div key={key} className="h-64 animate-pulse rounded-card bg-secondary-100" />)}</div>;
  if (isError) return <div className="rounded-card border border-danger/30 p-5 text-danger">Could not load plans. <button onClick={() => refetch()} className="underline">Retry</button></div>;
  return <div className="space-y-6"><div className="flex flex-wrap items-end justify-between gap-3"><div><h1 className="text-page-title text-ink-primary">Subscription plans</h1><p className="mt-1 text-secondary text-ink-secondary">Manage the packages available to RehabYangu facilities.</p></div><button onClick={() => setCreating(true)} className="btn-primary"><PlusIcon className="h-4 w-4" />Add plan</button></div><div className="grid gap-4 lg:grid-cols-3">{data?.map((plan) => <article key={plan.id} className="rounded-card border border-border bg-surface p-5 shadow-card"><div className="flex justify-between gap-3"><div><h2 className="text-component-title text-ink-primary">{plan.name}</h2><p className="mt-1 text-sm text-ink-secondary">{plan.description}</p></div><span className={`badge ${plan.is_active ? 'badge-active' : 'badge-suspended'}`}>{plan.is_active ? 'Active' : 'Inactive'}</span></div><p className="mt-5 text-2xl font-semibold text-ink-primary">{money(plan.price_monthly)}<span className="text-sm font-normal text-ink-secondary"> / month</span></p><p className="mt-1 text-sm text-ink-secondary">{plan.max_users === null ? 'Unlimited users' : `Up to ${plan.max_users} users`}</p><div className="mt-4 flex flex-wrap gap-1.5">{Object.entries(plan.feature_flags).filter(([, enabled]) => enabled).map(([name]) => <span className="rounded-full bg-secondary-100 px-2 py-1 text-caption text-ink-secondary" key={name}>{name.replace('_', ' ')}</span>)}</div><button onClick={() => setEditing(plan)} className="btn-secondary mt-5 w-full justify-center"><PencilSquareIcon className="h-4 w-4" />Edit</button></article>)}</div>{creating && <PlanForm onClose={() => setCreating(false)} />}{editing && <PlanForm plan={editing} onClose={() => setEditing(undefined)} />}</div>; }
