import { useState } from 'react';
import { Link } from '@tanstack/react-router';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { PlusIcon, EllipsisHorizontalIcon, BuildingOffice2Icon, UsersIcon, BanknotesIcon } from '@heroicons/react/24/outline';
import { adminApi, type Plan, type Tenant } from '../../api/admin';
import { Modal } from '../../components/ui/Modal';
import { useToast } from '../../context/ToastContext';

const money = (value?: string) => new Intl.NumberFormat('en-KE', { style: 'currency', currency: 'KES', maximumFractionDigits: 0 }).format(Number(value || 0));
const date = (value: string | null) => value ? new Intl.DateTimeFormat('en-KE', { dateStyle: 'medium' }).format(new Date(value)) : '—';
const statusClass = (status: Tenant['status']) => ({ active: 'badge-active', trial: 'badge-trial', overdue: 'badge-overdue', suspended: 'badge-suspended' })[status];

function AddTenant({ plans, onClose }: { plans: Plan[]; onClose: () => void }) {
  const activePlans = plans.filter((plan) => plan.is_active);
  const [form, setForm] = useState({ tenant_name: '', subdomain: '', admin_first_name: '', admin_last_name: '', admin_email: '', subscription_plan: String(activePlans[0]?.id || '') });
  const qc = useQueryClient(); const { showToast } = useToast();
  const mutation = useMutation({ mutationFn: () => adminApi.createTenant({ ...form, subscription_plan: Number(form.subscription_plan) }), onSuccess: () => { qc.invalidateQueries({ queryKey: ['admin-tenants'] }); qc.invalidateQueries({ queryKey: ['admin-stats'] }); showToast('Tenant created and administrator invitation issued.', 'success'); onClose(); } });
  const selected = activePlans.find((plan) => plan.id === Number(form.subscription_plan));
  const slugify = (value: string) => value.toLowerCase().trim().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '');
  const error = mutation.error as { response?: { data?: { subdomain?: string[]; admin_email?: string[] } } };
  return <Modal open onOpenChange={(open) => !open && onClose()} title="Add new tenant"><form className="space-y-4" onSubmit={(event) => { event.preventDefault(); mutation.mutate(); }}>
    <div className="grid gap-4 sm:grid-cols-2"><label className="form-label sm:col-span-2">Facility name<input required className="input-field mt-1" value={form.tenant_name} onChange={(e) => setForm({ ...form, tenant_name: e.target.value, subdomain: form.subdomain || slugify(e.target.value) })} /></label><label className="form-label sm:col-span-2">Tenant URL<input required pattern="[a-z0-9-]+" className="input-field mt-1" value={form.subdomain} onChange={(e) => setForm({ ...form, subdomain: slugify(e.target.value) })} /><span className="mt-1 block text-caption font-normal text-ink-secondary">https://{form.subdomain || 'your-facility'}.rehabyangu.com</span></label><label className="form-label">Administrator first name<input required className="input-field mt-1" value={form.admin_first_name} onChange={(e) => setForm({ ...form, admin_first_name: e.target.value })} /></label><label className="form-label">Administrator last name<input required className="input-field mt-1" value={form.admin_last_name} onChange={(e) => setForm({ ...form, admin_last_name: e.target.value })} /></label><label className="form-label sm:col-span-2">Administrator email<input required type="email" className="input-field mt-1" value={form.admin_email} onChange={(e) => setForm({ ...form, admin_email: e.target.value })} /></label></div>
    <label className="form-label">Subscription plan<select required className="input-field mt-1" value={form.subscription_plan} onChange={(e) => setForm({ ...form, subscription_plan: e.target.value })}>{activePlans.map((plan) => <option key={plan.id} value={plan.id}>{plan.name} — {money(plan.price_monthly)}/month</option>)}</select></label>
    {selected && <div className="rounded-btn bg-secondary-50 p-3 text-sm text-ink-secondary"><strong className="text-ink-primary">{selected.name}</strong> · {money(selected.price_monthly)}/month · {selected.max_users === null ? 'Unlimited users' : `Up to ${selected.max_users} users`}</div>}
    {mutation.isError && <p role="alert" className="text-sm text-danger">{error.response?.data?.subdomain?.[0] || error.response?.data?.admin_email?.[0] || 'Tenant creation failed. Please review the details.'}</p>}<button disabled={mutation.isPending || !selected} className="btn-primary w-full justify-center">{mutation.isPending ? 'Creating tenant…' : 'Create tenant & invite administrator'}</button>
  </form></Modal>;
}

export default function Tenants() {
  const [search, setSearch] = useState(''); const [status, setStatus] = useState(''); const [plan, setPlan] = useState(''); const [addOpen, setAddOpen] = useState(false); const [menu, setMenu] = useState<number | null>(null); const [confirmTenant, setConfirmTenant] = useState<Tenant | null>(null);
  const qc = useQueryClient(); const { showToast } = useToast();
  const query = useQuery({ queryKey: ['admin-tenants', search, status, plan], queryFn: () => adminApi.tenants({ search, status, plan }) });
  const stats = useQuery({ queryKey: ['admin-stats'], queryFn: adminApi.stats }); const plans = useQuery({ queryKey: ['admin-plans'], queryFn: adminApi.plans });
  const change = useMutation({ mutationFn: ({ id, action }: { id: number; action: string }) => adminApi.updateTenant(id, { action }), onSuccess: () => { qc.invalidateQueries({ queryKey: ['admin-tenants'] }); qc.invalidateQueries({ queryKey: ['admin-stats'] }); showToast('Tenant status updated.', 'success'); } });
  const cards = [{ label: 'Active tenants', value: stats.data?.active_tenants ?? 0, icon: BuildingOffice2Icon }, { label: 'Trial tenants', value: stats.data?.trial_tenants ?? 0, icon: BuildingOffice2Icon }, { label: 'Total users', value: stats.data?.total_users ?? 0, icon: UsersIcon }, { label: 'New this month', value: stats.data?.new_tenants_this_month ?? 0, icon: BuildingOffice2Icon }];
  const tenants = query.data?.results || [];
  return <div className="space-y-6"><div className="flex flex-wrap items-end justify-between gap-3"><div><h1 className="text-page-title text-ink-primary">RehabYangu Platform Administration</h1><p className="mt-1 text-secondary text-ink-secondary">Manage tenants, subscriptions and platform operations.</p></div><button onClick={() => setAddOpen(true)} className="btn-primary"><PlusIcon className="h-4 w-4" />Add tenant</button></div>
    <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5">{cards.map(({ label, value, icon: Icon }) => <div key={label} className="rounded-card border border-border bg-surface p-4"><Icon className="mb-3 h-5 w-5 text-primary" /><p className="text-sm text-ink-secondary">{label}</p><p className="mt-1 text-2xl font-semibold text-ink-primary">{value}</p></div>)}<div className="rounded-card border border-primary/20 bg-primary-subtle p-4"><BanknotesIcon className="mb-3 h-5 w-5 text-primary" /><p className="text-sm text-ink-secondary">MRR <span className="text-caption">(paid tenants)</span></p><p className="mt-1 text-2xl font-semibold text-ink-primary">{money(stats.data?.mrr)}</p></div></section>
    <div className="text-sm text-ink-secondary">Total: <strong>{stats.data?.total_tenants ?? 0}</strong> · Overdue: <strong>{stats.data?.overdue_tenants ?? 0}</strong> · Suspended: <strong>{stats.data?.suspended_tenants ?? 0}</strong></div>
    <section className="rounded-card border border-border bg-surface"><div className="flex flex-wrap gap-3 border-b border-border p-4"><input aria-label="Search tenants" placeholder="Search facility or subdomain" className="input-field max-w-sm" value={search} onChange={(e) => setSearch(e.target.value)} /><select aria-label="Filter status" className="input-field w-auto" value={status} onChange={(e) => setStatus(e.target.value)}><option value="">All statuses</option>{['active','trial','overdue','suspended'].map((item) => <option key={item} value={item}>{item}</option>)}</select><select aria-label="Filter plan" className="input-field w-auto" value={plan} onChange={(e) => setPlan(e.target.value)}><option value="">All plans</option>{plans.data?.map((item) => <option key={item.id} value={item.code}>{item.name}</option>)}</select></div>
      {query.isLoading ? <div className="space-y-3 p-4">{[1,2,3].map((item) => <div key={item} className="h-14 animate-pulse rounded bg-secondary-100" />)}</div> : query.isError ? <div className="p-6 text-danger">Could not load tenants. <button onClick={() => query.refetch()} className="underline">Retry</button></div> : tenants.length === 0 ? <div className="p-10 text-center"><p className="font-medium text-ink-primary">No rehabilitation centres match these filters.</p></div> : <div className="overflow-x-auto"><table className="min-w-[850px] w-full text-left text-sm"><thead className="bg-secondary-50 text-caption uppercase tracking-wide text-ink-secondary"><tr>{['Tenant','Plan','Monthly price','Status','Users','Trial / billing','Actions'].map((label) => <th className="px-4 py-3 font-semibold" key={label}>{label}</th>)}</tr></thead><tbody className="divide-y divide-border">{tenants.map((tenant) => <tr key={tenant.id}><td className="px-4 py-3"><Link to="/admin/tenants/$tenantId" params={{ tenantId: String(tenant.id) }} className="font-semibold text-ink-primary hover:text-primary">{tenant.name}</Link><p className="text-caption text-ink-secondary">{tenant.subdomain}.rehabyangu.com</p></td><td className="px-4 py-3">{tenant.plan?.name || 'Unassigned'}</td><td className="px-4 py-3">{tenant.plan ? money(tenant.plan.price_monthly) : '—'}</td><td className="px-4 py-3"><span className={`badge ${statusClass(tenant.status)}`}>{tenant.status}</span></td><td className="px-4 py-3">{tenant.user_count} / {tenant.max_users ?? 'Unlimited'}</td><td className="px-4 py-3">{date(tenant.status === 'trial' ? tenant.trial_ends_at : tenant.next_billing_date)}</td><td className="relative px-4 py-3"><button aria-label={`Actions for ${tenant.name}`} onClick={() => setMenu(menu === tenant.id ? null : tenant.id)} className="grid h-11 w-11 place-items-center rounded-btn hover:bg-secondary-100"><EllipsisHorizontalIcon className="h-5 w-5" /></button>{menu === tenant.id && <div className="absolute right-4 z-10 mt-1 w-40 rounded-card border border-border bg-surface p-1 shadow-dropdown"><Link to="/admin/tenants/$tenantId" params={{ tenantId: String(tenant.id) }} className="flex min-h-10 items-center px-3 hover:bg-secondary-50">View</Link><Link to="/admin/tenants/$tenantId" params={{ tenantId: String(tenant.id) }} className="flex min-h-10 items-center px-3 hover:bg-secondary-50">Change plan</Link><button onClick={() => { setMenu(null); setConfirmTenant(tenant); }} className="flex min-h-10 w-full items-center px-3 text-left hover:bg-secondary-50">{tenant.status === 'suspended' ? 'Activate' : 'Suspend'}</button></div>}</td></tr>)}</tbody></table></div>}
    </section>{addOpen && <AddTenant plans={plans.data || []} onClose={() => setAddOpen(false)} />}{confirmTenant && <Modal open onOpenChange={(open) => !open && setConfirmTenant(null)} title={confirmTenant.status === 'suspended' ? 'Restore tenant' : 'Suspend tenant'}><p className="text-secondary text-ink-secondary">{confirmTenant.status === 'suspended' ? 'Restore access for this tenant?' : 'Suspend this tenant and block workspace access?'} This is recorded in the immutable audit log.</p><div className="mt-6 flex justify-end gap-3"><button className="btn-secondary" onClick={() => setConfirmTenant(null)}>Cancel</button><button disabled={change.isPending} className="btn-primary" onClick={() => change.mutate({ id: confirmTenant.id, action: confirmTenant.status === 'suspended' ? 'restore' : 'suspend' }, { onSuccess: () => setConfirmTenant(null) })}>{change.isPending ? 'Working…' : confirmTenant.status === 'suspended' ? 'Restore' : 'Suspend'}</button></div></Modal>}</div>;
}
