import { useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Link, useParams } from '@tanstack/react-router';
import { adminApi, type Plan } from '../../api/admin';
import { Modal } from '../../components/ui/Modal';
import { useToast } from '../../context/ToastContext';
import { displayRole } from '../../utils/roles';

const money = (value?: string) => new Intl.NumberFormat('en-KE', { style: 'currency', currency: 'KES', maximumFractionDigits: 0 }).format(Number(value || 0));
const date = (value?: string | null) => value ? new Intl.DateTimeFormat('en-KE', { dateStyle: 'long' }).format(new Date(value)) : 'Not scheduled';
const timestamp = (value?: string | null) => value ? new Intl.DateTimeFormat('en-KE', { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(value)) : 'Never';
const features = (plan?: Plan | null) => Object.entries(plan?.feature_flags || {}).filter(([, enabled]) => enabled).map(([key]) => key.replace(/_/g, ' '));

function Confirm({ title, message, confirmLabel, busy, onConfirm, onClose }: { title: string; message: string; confirmLabel: string; busy: boolean; onConfirm: () => void; onClose: () => void }) {
  return <Modal open onOpenChange={(open) => !open && onClose()} title={title}><p className="text-secondary text-ink-secondary">{message}</p><div className="mt-6 flex justify-end gap-3"><button onClick={onClose} className="btn-secondary">Cancel</button><button disabled={busy} onClick={onConfirm} className="btn-primary">{busy ? 'Working…' : confirmLabel}</button></div></Modal>;
}

export default function TenantDetail() {
  const { tenantId } = useParams({ from: '/admin/tenants/$tenantId' }); const qc = useQueryClient(); const { showToast } = useToast();
  const [dialog, setDialog] = useState<'plan' | 'suspend' | 'activate' | 'deactivate' | 'archive' | null>(null); const [selectedPlan, setSelectedPlan] = useState('');
  const query = useQuery({ queryKey: ['admin-tenant', tenantId], queryFn: () => adminApi.tenant(tenantId) });
  const plans = useQuery({ queryKey: ['admin-plans'], queryFn: adminApi.plans });
  const refresh = () => { qc.invalidateQueries({ queryKey: ['admin-tenant', tenantId] }); qc.invalidateQueries({ queryKey: ['admin-tenants'] }); qc.invalidateQueries({ queryKey: ['admin-stats'] }); };
  const update = useMutation({ mutationFn: (body: Record<string, unknown>) => adminApi.updateTenant(Number(tenantId), body), onSuccess: () => { refresh(); setDialog(null); showToast('Tenant updated.', 'success'); }, onError: () => showToast('The tenant action was rejected. Please review its current state.', 'error') });
  const reminder = useMutation({ mutationFn: () => adminApi.sendPaymentReminder(Number(tenantId)), onSuccess: (result) => { refresh(); showToast(result.message, 'success'); }, onError: () => showToast('Unable to send the payment reminder.', 'error') });
  if (query.isLoading) return <div className="space-y-4"><div className="h-12 w-64 animate-pulse rounded bg-secondary-100" /><div className="h-72 animate-pulse rounded-card bg-secondary-100" /></div>;
  if (query.isError || !query.data) return <div className="text-danger">Unable to load this tenant. <button onClick={() => query.refetch()} className="underline">Retry</button></div>;
  const tenant = query.data; const selectablePlans = (plans.data || []).filter((plan) => plan.is_active && plan.id !== tenant.plan?.id); const action = tenant.status === 'suspended' ? 'restore' : 'suspend';
  return <div className="space-y-6"><Link to="/admin" className="text-sm font-medium text-primary hover:underline">← All tenants</Link>
    <div className="flex flex-wrap items-start justify-between gap-4"><div className="flex gap-3">{tenant.logo_url && <img src={tenant.logo_url} alt="" className="h-12 w-12 rounded-card object-contain" />}<div><h1 className="text-page-title text-ink-primary">{tenant.name}</h1><p className="mt-1 text-secondary text-ink-secondary">{tenant.subdomain}.rehabyangu.com</p></div></div><span className={`badge ${tenant.archived_at ? 'badge-suspended' : 'badge-active'}`}>{tenant.archived_at ? 'archived' : tenant.status}</span></div>
    <div className="grid gap-4 lg:grid-cols-3"><section className="rounded-card border border-border bg-surface p-5 lg:col-span-2"><h2 className="text-component-title text-ink-primary">Subscription health</h2><dl className="mt-4 grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{[['Current plan', tenant.plan?.name || 'Unassigned'], ['Monthly price', money(tenant.monthly_fee || tenant.plan?.price_monthly)], ['Users', `${tenant.user_count} / ${tenant.max_users ?? 'Unlimited'}`], ['Trial ends', date(tenant.trial_ends_at)], ['Next billing date', date(tenant.next_billing_date)], ['Grace period ends', date(tenant.grace_period_end)], ['Days remaining', tenant.days_remaining === null ? 'Not scheduled' : `${tenant.days_remaining} days`]].map(([label, value]) => <div key={label}><dt className="text-caption text-ink-secondary">{label}</dt><dd className="mt-1 font-medium text-ink-primary">{value}</dd></div>)}</dl><div className="mt-5 border-t border-border pt-4"><p className="text-caption text-ink-secondary">Plan features</p><p className="mt-1 text-sm text-ink-primary">{features(tenant.plan).length ? features(tenant.plan).join(', ') : 'No enabled features'}</p></div></section>
      <section className="rounded-card border border-border bg-surface p-5"><h2 className="text-component-title text-ink-primary">Administration</h2><p className="mt-3 text-sm text-ink-secondary">{tenant.administrator ? `${tenant.administrator.name} · ${tenant.administrator.email}` : 'No accepted administrator yet.'}</p><div className="mt-5 space-y-2"><button disabled={update.isPending || !selectablePlans.length} onClick={() => { setSelectedPlan(String(selectablePlans[0]?.id || '')); setDialog('plan'); }} className="btn-secondary w-full justify-center">Change plan</button><button disabled={update.isPending || Boolean(tenant.archived_at)} onClick={() => setDialog(action === 'restore' ? 'activate' : 'suspend')} className="btn-secondary w-full justify-center">{action === 'restore' ? 'Restore' : 'Suspend'} account</button><button disabled={reminder.isPending || Boolean(tenant.archived_at)} onClick={() => reminder.mutate()} className="btn-secondary w-full justify-center">{reminder.isPending ? 'Sending…' : 'Send payment reminder'}</button><button disabled={update.isPending || Boolean(tenant.archived_at)} onClick={() => setDialog('deactivate')} className="btn-secondary w-full justify-center">Deactivate</button><button disabled={update.isPending || Boolean(tenant.archived_at)} onClick={() => setDialog('archive')} className="w-full rounded-btn border border-danger/40 px-3 py-2 text-sm font-semibold text-danger">Archive tenant</button></div></section></div>
    <section className="rounded-card border border-border bg-surface p-5"><h2 className="text-component-title text-ink-primary">Tenant usage</h2><p className="mt-1 text-sm text-ink-secondary">{tenant.active_user_count} active users · {tenant.active_member_count} active staff members</p><div className="mt-4 overflow-x-auto"><table className="min-w-[760px] w-full text-left text-sm"><thead className="text-caption text-ink-secondary"><tr>{['Member', 'Role', 'Administrator', 'Tenant user ID', 'Status', 'Last login'].map((label) => <th key={label} className="border-b border-border px-3 py-2">{label}</th>)}</tr></thead><tbody>{tenant.members?.map((member) => <tr key={`${member.email}-${member.tenant_user_id}`}><td className="border-b border-border px-3 py-3"><p className="font-medium text-ink-primary">{member.name}</p><p className="text-caption text-ink-secondary">{member.email}</p></td><td className="border-b border-border px-3 py-3">{displayRole(member)}</td><td className="border-b border-border px-3 py-3">{member.is_rehab_admin ? 'Yes' : 'No'}</td><td className="border-b border-border px-3 py-3">{member.tenant_user_id || '—'}</td><td className="border-b border-border px-3 py-3">{member.is_active ? 'Active' : 'Inactive'}</td><td className="border-b border-border px-3 py-3">{timestamp(member.last_login)}</td></tr>)}</tbody></table></div></section>
    <section className="rounded-card border border-border bg-surface p-5"><h2 className="text-component-title text-ink-primary">Recent administration activity</h2><ul className="mt-4 divide-y divide-border">{tenant.recent_audit_events?.length ? tenant.recent_audit_events.map((event, index) => <li key={`${event.timestamp}-${index}`} className="py-3 text-sm"><p className="text-ink-primary">{event.description}</p><p className="mt-1 text-caption text-ink-secondary">{event.actor} · {event.action} · {timestamp(event.timestamp)}</p></li>) : <li className="py-3 text-sm text-ink-secondary">No administration activity recorded.</li>}</ul></section>
    {dialog === 'plan' && <Modal open onOpenChange={(open) => !open && setDialog(null)} title="Change subscription plan"><p className="text-secondary text-ink-secondary">The monthly fee will change to the selected plan price. Trial, grace, and billing dates are preserved.</p><label className="form-label mt-4 block">New plan<select className="input-field mt-1" value={selectedPlan} onChange={(event) => setSelectedPlan(event.target.value)}>{selectablePlans.map((plan) => <option key={plan.id} value={plan.id}>{plan.name} — {money(plan.price_monthly)}/month</option>)}</select></label><div className="mt-6 flex justify-end gap-3"><button onClick={() => setDialog(null)} className="btn-secondary">Cancel</button><button disabled={update.isPending || !selectedPlan} onClick={() => update.mutate({ subscription_plan: Number(selectedPlan) })} className="btn-primary">{update.isPending ? 'Changing…' : 'Change plan'}</button></div></Modal>}
    {dialog === 'suspend' && <Confirm title="Suspend tenant" message="Suspending blocks access for this tenant. This can be restored later and is recorded in the immutable audit log." confirmLabel="Suspend tenant" busy={update.isPending} onConfirm={() => update.mutate({ action: 'suspend' })} onClose={() => setDialog(null)} />}
    {dialog === 'activate' && <Confirm title="Restore tenant" message="Restoring re-enables tenant access. The action is recorded in the immutable audit log." confirmLabel="Restore tenant" busy={update.isPending} onConfirm={() => update.mutate({ action: 'restore' })} onClose={() => setDialog(null)} />}
    {dialog === 'deactivate' && <Confirm title="Deactivate tenant" message="Deactivation disables access without deleting healthcare data. Archive is available for retired tenants." confirmLabel="Deactivate" busy={update.isPending} onConfirm={() => update.mutate({ action: 'deactivate' })} onClose={() => setDialog(null)} />}
    {dialog === 'archive' && <Confirm title="Archive tenant" message="Archiving disables access and retains healthcare, billing, and audit history. It does not permanently delete data." confirmLabel="Archive tenant" busy={update.isPending} onConfirm={() => update.mutate({ action: 'archive' })} onClose={() => setDialog(null)} />}
  </div>;
}
