# Generated by Django 6.0.7 on 2026-07-28 17:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('super_admin', 'Super Admin (Weiraro)'), ('rehab_admin', 'Rehab Admin (Director)'), ('psychiatrist', 'Psychiatrist'), ('clinical_officer', 'Clinical Officer'), ('nurse', 'Nurse'), ('counselor', 'Counselor'), ('pharmacist', 'Pharmacist'), ('receptionist', 'Receptionist'), ('accountant', 'Accountant'), ('store_manager', 'Store Manager'), ('hr_manager', 'HR Manager'), ('cook', 'Cook'), ('other', 'Other')], default='other', max_length=50)),
                ('is_rehab_admin', models.BooleanField(default=False)),
                ('is_super_admin', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='tenants.tenant')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
