# Generated by Django 6.0.7 on 2026-07-29 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='extra_permissions',
            field=models.ManyToManyField(blank=True, related_name='granted_to_users', to='authorization.permission'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='roles',
            field=models.ManyToManyField(blank=True, to='authorization.role'),
        ),
    ]
