# Generated by Django 6.0.7 on 2026-08-02 13:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_tenantconfig'),
        ('users', '0002_userprofile_extra_permissions_userprofile_roles'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('super_admin', 'Super Admin (Weiraro)'), ('rehab_admin', 'Rehab Admin (Director)'), ('psychiatrist', 'Psychiatrist'), ('clinical_officer', 'Clinical Officer'), ('nurse', 'Nurse'), ('counselor', 'Counselor'), ('pharmacist', 'Pharmacist'), ('receptionist', 'Receptionist'), ('accountant', 'Accountant'), ('store_manager', 'Store Manager'), ('hr_manager', 'HR Manager'), ('cook', 'Cook'), ('other', 'Other')], default='other', max_length=50)),
                ('is_rehab_admin', models.BooleanField(default=False)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='tenants.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tenant Membership',
                'verbose_name_plural': 'Tenant Memberships',
                'unique_together': {('user', 'tenant')},
            },
        ),
    ]
