# Generated by Django 6.0.7 on 2026-08-02 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_tenantmembership'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='is_rehab_admin',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='is_super_admin',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='role',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='tenant',
        ),
    ]
