# Generated by Django 6.0.7 on 2026-08-02 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantmembership',
            name='tenant_user_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
